export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_CLOCKIN_REQUEST = "USER_CLOCKIN_REQUEST";
export const USER_CLOCKIN_SUCCESS = "USER_CLOCKIN_SUCCESS";
export const USER_CLOCKIN_FAIL = "USER_CLOCKIN_FAIL";
export const USER_CLOCKIN_RESET = "USER_CLOCKIN_RESET";

export const USER_CLOCKOUT_REQUEST = "USER_CLOCKOUT_REQUEST";
export const USER_CLOCKOUT_SUCCESS = "USER_CLOCKOUT_SUCCESS";
export const USER_CLOCKOUT_FAIL = "USER_CLOCKOUT_FAIL";
export const USER_CLOCKOUT_RESET = "USER_CLOCKOUT_RESET";
